# Generated by Django 4.2.20 on 2025-06-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(),
        ),
    ]
